server:
    port: 8080

spring:
    profiles:
        active: local
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:aq-project}
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:}
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                format_sql: true
        show-sql: true

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        url: /v3/api-docs
        display-request-duration: true
        groups-order: ASC
